# Generated by Django 5.1.1 on 2024-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
