# Generated by Django 5.1.1 on 2025-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('concert', 'Концерт'), ('theater', 'Театр'), ('cinema', 'Кино'), ('exhibition', 'Выставка'), ('lecture', 'Лекция'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
