# Generated by Django 3.2.16 on 2026-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_past',
            field=models.BooleanField(default=False, verbose_name='Прошедшее'),
        ),
    ]
