# Generated by Django 3.2.16 on 2026-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bride_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя невесты'),
        ),
        migrations.AddField(
            model_name='event',
            name='groom_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя жениха'),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ожидаемое количество гостей'),
        ),
        migrations.AddField(
            model_name='event',
            name='wedding_theme',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема свадьбы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Концерт'), ('theater', 'Театр'), ('cinema', 'Кино'), ('exhibition', 'Выставка'), ('lecture', 'Лекция'), ('wedding', 'Свадьба'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип мероприятия'),
        ),
    ]
