# Generated by Django 3.2.16 on 2026-06-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20260630_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ доступа'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватное мероприятие'),
        ),
    ]
